/********************************************************************
* LinkDef_out.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LinkDef_out.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLinkDef_out();
extern void G__cpp_setup_inheritanceLinkDef_out();
extern void G__cpp_setup_typetableLinkDef_out();
extern void G__cpp_setup_memvarLinkDef_out();
extern void G__cpp_setup_globalLinkDef_out();
extern void G__cpp_setup_memfuncLinkDef_out();
extern void G__cpp_setup_funcLinkDef_out();
extern void G__set_cpp_environmentLinkDef_out();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MyScanChain.h"
#include "PlotUtilities.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LinkDef_outLN_string;
extern G__linked_taginfo G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDef_outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LinkDef_outLN_TChain;
extern G__linked_taginfo G__LinkDef_outLN_MyScanChain;
extern G__linked_taginfo G__LinkDef_outLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TVectorTlEdoublegR;

/* STUB derived class for protected member access */
