//
// File generated by rootcint at Wed Aug 28 09:52:45 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME LinkDef_out
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "LinkDef_out.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void MyScanChain_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void MyScanChain_Dictionary();
   static void *new_MyScanChain(void *p = 0);
   static void *newArray_MyScanChain(Long_t size, void *p);
   static void delete_MyScanChain(void *p);
   static void deleteArray_MyScanChain(void *p);
   static void destruct_MyScanChain(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::MyScanChain*)
   {
      ::MyScanChain *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::MyScanChain),0);
      static ::ROOT::TGenericClassInfo 
         instance("MyScanChain", "./MyScanChain.h", 23,
                  typeid(::MyScanChain), DefineBehavior(ptr, ptr),
                  0, &MyScanChain_Dictionary, isa_proxy, 0,
                  sizeof(::MyScanChain) );
      instance.SetNew(&new_MyScanChain);
      instance.SetNewArray(&newArray_MyScanChain);
      instance.SetDelete(&delete_MyScanChain);
      instance.SetDeleteArray(&deleteArray_MyScanChain);
      instance.SetDestructor(&destruct_MyScanChain);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::MyScanChain*)
   {
      return GenerateInitInstanceLocal((::MyScanChain*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MyScanChain*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void MyScanChain_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::MyScanChain*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_MyScanChain(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MyScanChain : new ::MyScanChain;
   }
   static void *newArray_MyScanChain(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MyScanChain[nElements] : new ::MyScanChain[nElements];
   }
   // Wrapper around operator delete
   static void delete_MyScanChain(void *p) {
      delete ((::MyScanChain*)p);
   }
   static void deleteArray_MyScanChain(void *p) {
      delete [] ((::MyScanChain*)p);
   }
   static void destruct_MyScanChain(void *p) {
      typedef ::MyScanChain current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::MyScanChain

/********************************************************
* LinkDef_out.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableLinkDef_out();

extern "C" void G__set_cpp_environmentLinkDef_out() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("MyScanChain.h");
  G__add_compiledheader("PlotUtilities.h");
  G__cpp_reset_tagtableLinkDef_out();
}
#include <new>
extern "C" int G__cpp_dllrevLinkDef_out() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MyScanChain */
static int G__LinkDef_out_212_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MyScanChain* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MyScanChain[n];
     } else {
       p = new((void*) gvp) MyScanChain[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MyScanChain;
     } else {
       p = new((void*) gvp) MyScanChain;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_212_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MyScanChain* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new MyScanChain(*((string*) G__int(libp->para[0])), (unsigned int) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) MyScanChain(*((string*) G__int(libp->para[0])), (unsigned int) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_212_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((MyScanChain*) G__getstructoffset())->ScanChain(*((string*) G__int(libp->para[0])), (TChain*) G__int(libp->para[1])
, *((string*) G__int(libp->para[2]))));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LinkDef_out_212_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MyScanChain* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MyScanChain(*(MyScanChain*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MyScanChain G__TMyScanChain;
static int G__LinkDef_out_212_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MyScanChain*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MyScanChain*) (soff+(sizeof(MyScanChain)*i)))->~G__TMyScanChain();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MyScanChain*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MyScanChain*) (soff))->~G__TMyScanChain();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LinkDef_out_212_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MyScanChain* dest = (MyScanChain*) G__getstructoffset();
   *dest = *(MyScanChain*) libp->para[0].ref;
   const MyScanChain& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */
static int G__LinkDef_out__0_1401(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      saveHist((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      saveHist((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out__0_1402(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      deleteHistos();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/* MyScanChain */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncLinkDef_out {
 public:
  G__Sizep2memfuncLinkDef_out(): p(&G__Sizep2memfuncLinkDef_out::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncLinkDef_out::*p)();
};

size_t G__get_sizep2memfuncLinkDef_out()
{
  G__Sizep2memfuncLinkDef_out a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceLinkDef_out() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableLinkDef_out() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LinkDef_outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LinkDef_outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MyScanChain */
static void G__setup_memvarMyScanChain(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain));
   { MyScanChain *p; p=(MyScanChain*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_string),-1,-1,4,"genPdfName_=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"genPdfSubset_=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarLinkDef_out() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMyScanChain(void) {
   /* MyScanChain */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain));
   G__memfunc_setup("MyScanChain",1070,G__LinkDef_out_212_0_1, 105, G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MyScanChain",1070,G__LinkDef_out_212_0_2, 105, G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain), -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - genPdfName h - - 0 - genPdfSubset", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ScanChain",872,G__LinkDef_out_212_0_3, 105, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 - sampleName U 'TChain' - 0 - chain "
"u 'string' - 0 - pdfName", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Cuts",415,(G__InterfaceMethod) NULL, 103, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("MyScanChain", 1070, G__LinkDef_out_212_0_5, (int) ('i'), G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain), -1, 0, 1, 1, 1, 0, "u 'MyScanChain' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MyScanChain", 1196, G__LinkDef_out_212_0_6, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LinkDef_out_212_0_7, (int) ('u'), G__get_linked_tagnum(&G__LinkDef_outLN_MyScanChain), -1, 1, 1, 1, 1, 0, "u 'MyScanChain' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncLinkDef_out() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalLinkDef_out() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
   G__memfunc_setup("saveHist", 839, G__LinkDef_out__0_1401, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - filename C - - 10 '\"*\"' pat", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("deleteHistos", 1261, G__LinkDef_out__0_1402, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcLinkDef_out() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__LinkDef_outLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__LinkDef_outLN_TChain = { "TChain" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_MyScanChain = { "MyScanChain" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableLinkDef_out() {
  G__LinkDef_outLN_string.tagnum = -1 ;
  G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LinkDef_outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__LinkDef_outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__LinkDef_outLN_TChain.tagnum = -1 ;
  G__LinkDef_outLN_MyScanChain.tagnum = -1 ;
  G__LinkDef_outLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TVectorTlEdoublegR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableLinkDef_out() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_string);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TChain);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__LinkDef_outLN_MyScanChain),sizeof(MyScanChain),-1,34048,(char*)NULL,G__setup_memvarMyScanChain,G__setup_memfuncMyScanChain);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TVectorTlEdoublegR);
}
extern "C" void G__cpp_setupLinkDef_out(void) {
  G__check_setup_version(30051515,"G__cpp_setupLinkDef_out()");
  G__set_cpp_environmentLinkDef_out();
  G__cpp_setup_tagtableLinkDef_out();

  G__cpp_setup_inheritanceLinkDef_out();

  G__cpp_setup_typetableLinkDef_out();

  G__cpp_setup_memvarLinkDef_out();

  G__cpp_setup_memfuncLinkDef_out();
  G__cpp_setup_globalLinkDef_out();
  G__cpp_setup_funcLinkDef_out();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncLinkDef_out();
  return;
}
class G__cpp_setup_initLinkDef_out {
  public:
    G__cpp_setup_initLinkDef_out() { G__add_setup_func("LinkDef_out",(G__incsetup)(&G__cpp_setupLinkDef_out)); G__call_setup_funcs(); }
   ~G__cpp_setup_initLinkDef_out() { G__remove_setup_func("LinkDef_out"); }
};
G__cpp_setup_initLinkDef_out G__cpp_setup_initializerLinkDef_out;

